/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acoples.visual;

/**
 *
 * @author Alba Proyecto
 */
public class Escala extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Escala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escala de colores para ln/h", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.add(jTextField1);

        jLabel3.setText("Diseñar como puntal tensor");
        jPanel1.add(jLabel3);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField3);

        jLabel1.setText("Diseñar con diagonales");
        jPanel1.add(jLabel1);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField5);

        jLabel6.setText("Recomendado diseñar como viga especial (SMF)");
        jPanel1.add(jLabel6);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jTextField4);

        jLabel4.setText("Diseñar como viga especial (SMF)");
        jPanel1.add(jLabel4);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.add(jTextField6);

        jLabel2.setText("Recomendado diseñar con diagonales");
        jPanel1.add(jLabel2);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jTextField2);

        jLabel5.setText("Modificar sección");
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escala de colores de error", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.add(jTextField7);

        jLabel7.setText("Errores de cálculo y/ó corrección del sistema sobre los mismos");
        jPanel2.add(jLabel7);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField8);

        jLabel8.setText("Datos correctos");
        jPanel2.add(jLabel8);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
