/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acoples.visual;

import acoples.comunes.Comun;
import acoples.comunes.Optener_serilizado;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alba Proyecto
 */
public class NewMDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    public NewMDIApplication() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        this.requestFocus();
        //desktopPane.add(Comun.np, CENTER_ALIGNMENT);
        //desktopPane.add(Comun.lv, CENTER_ALIGNMENT);
        //desktopPane.add(Comun.vc, CENTER_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        abrir = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        memoria = new javax.swing.JMenuItem();
        diagrama = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("ALBA PROYECTO ESTRUCTURAL");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        desktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/edificio-de-banco (3).png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Proyecto");

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/icons8-Microsoft Excel-16.png"))); // NOI18N
        nuevo.setMnemonic('s');
        nuevo.setText("Nuevo Proyecto");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        nuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nuevoKeyPressed(evt);
            }
        });
        fileMenu.add(nuevo);

        abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/HD-open-icon.png"))); // NOI18N
        abrir.setText("Abrir Proyecto");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        abrir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                abrirKeyPressed(evt);
            }
        });
        fileMenu.add(abrir);

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Actions-exit-icon.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        exitMenuItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                exitMenuItemKeyPressed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/document-help-and-support-icon.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Book-icon.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Manual de uso");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        contentMenuItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contentMenuItemKeyPressed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Apps-colors-icon.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Escala de colores");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/chart-pie-icon.png"))); // NOI18N
        jMenuItem1.setText("Gráfico");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuItem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem1KeyPressed(evt);
            }
        });
        helpMenu.add(jMenuItem1);

        memoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/edu-mathematics-icon.png"))); // NOI18N
        memoria.setText("Memoria");
        memoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoriaActionPerformed(evt);
            }
        });
        memoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                memoriaKeyPressed(evt);
            }
        });
        helpMenu.add(memoria);

        diagrama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/diagram-icon.png"))); // NOI18N
        diagrama.setText("Diagrama de flujo");
        diagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagramaActionPerformed(evt);
            }
        });
        diagrama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                diagramaKeyPressed(evt);
            }
        });
        helpMenu.add(diagrama);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        //Nombrar_pryecto np=new Nombrar_pryecto();
        //Comun.np.setVisible(true);
        Nombrar_pryecto np = new Nombrar_pryecto();
        desktopPane.add(np, CENTER_ALIGNMENT);
        np.setVisible(true);
        //nuevo.setEnabled(false);
        //abrir.setEnabled(false);
    }//GEN-LAST:event_nuevoActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        // TODO add your handling code here:
        Optener_serilizado obs = new Optener_serilizado();
    }//GEN-LAST:event_abrirActionPerformed

    private void abrirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_abrirKeyPressed
        // TODO add your handling code here:
        Optener_serilizado obs = new Optener_serilizado();
    }//GEN-LAST:event_abrirKeyPressed

    private void nuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuevoKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        //Nombrar_pryecto np=new Nombrar_pryecto();
        //Comun.np.setVisible(true);
        Nombrar_pryecto np = new Nombrar_pryecto();
        desktopPane.add(np, CENTER_ALIGNMENT);
        np.setVisible(true);
        //nuevo.setEnabled(false);
        //abrir.setEnabled(false);
    }//GEN-LAST:event_nuevoKeyPressed

    private void exitMenuItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exitMenuItemKeyPressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemKeyPressed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        //desktopPane.add(es, CENTER_ALIGNMENT);
        Comun.es.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:        
        try {
            String url_pdf = "viga.pdf";
            String url_png = "viga.png";
            String url_jpeg = "viga_scala.jpeg";
            String url_xps = "memoria_va.xps";
            String url_manual = "Manual_VA.docx";
            ProcessBuilder p = new ProcessBuilder();
            //ojo esto solo se está utilizando para sistema operativo windows
            p.command("cmd.exe", "/c", url_manual);
            //p.command("cmd.exe", "/c", url_png);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(NewMDIApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void contentMenuItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contentMenuItemKeyPressed
        // TODO add your handling code here:
        try {
            String url_pdf = "viga.pdf";
            String url_png = "viga.png";
            String url_jpeg = "viga_scala.jpeg";
            String url_xps = "memoria_va.xps";
            String url_manual = "Manual_VA.docx";
            ProcessBuilder p = new ProcessBuilder();
            //ojo esto solo se está utilizando para sistema operativo windows
            p.command("cmd.exe", "/c", url_manual);
            //p.command("cmd.exe", "/c", url_png);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(NewMDIApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_contentMenuItemKeyPressed

    private void memoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoriaActionPerformed
        // TODO add your handling code here:
        try {
            String url_pdf = "viga.pdf";
            String url_png = "viga.png";
            String url_jpeg = "viga_scala.jpeg";
            String url_xps = "memoria_va.xps";
            ProcessBuilder p = new ProcessBuilder();
            //ojo esto solo se está utilizando para sistema operativo windows
            p.command("cmd.exe", "/c", url_xps);
            //p.command("cmd.exe", "/c", url_png);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(NewMDIApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_memoriaActionPerformed

    private void memoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memoriaKeyPressed
        // TODO add your handling code here:
         try {
            String url_pdf = "viga.pdf";
            String url_png = "viga.png";
            String url_jpeg = "viga_scala.jpeg";
            String url_xps = "memoria_va.xps";
            ProcessBuilder p = new ProcessBuilder();
            //ojo esto solo se está utilizando para sistema operativo windows
            p.command("cmd.exe", "/c", url_xps);
            //p.command("cmd.exe", "/c", url_png);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(NewMDIApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_memoriaKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         try {
            String url_pdf = "viga.pdf";
            String url_png = "viga.png";
            String url_jpeg = "viga_scala.jpeg";
            String url_xps = "memoria_va.xps";
            ProcessBuilder p = new ProcessBuilder();
            //ojo esto solo se está utilizando para sistema operativo windows
            p.command("cmd.exe", "/c", url_jpeg);
            //p.command("cmd.exe", "/c", url_png);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(NewMDIApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem1KeyPressed
        // TODO add your handling code here:
         try {
            String url_pdf = "viga.pdf";
            String url_png = "viga.png";
            String url_jpeg = "viga_scala.jpeg";
            String url_xps = "memoria_va.xps";
            ProcessBuilder p = new ProcessBuilder();
            //ojo esto solo se está utilizando para sistema operativo windows
            p.command("cmd.exe", "/c", url_jpeg);
            //p.command("cmd.exe", "/c", url_png);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(NewMDIApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1KeyPressed

    private void diagramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagramaActionPerformed
        // TODO add your handling code here:
        try {
            String url_pdf = "viga.pdf";
            String url_png = "viga.png";
            String url_jpeg = "viga_scala.jpeg";
            String url_xps = "memoria_va.xps";
            ProcessBuilder p = new ProcessBuilder();
            //ojo esto solo se está utilizando para sistema operativo windows
            p.command("cmd.exe", "/c", url_pdf);
            //p.command("cmd.exe", "/c", url_png);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(NewMDIApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_diagramaActionPerformed

    private void diagramaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diagramaKeyPressed
        // TODO add your handling code here:
        try {
            String url_pdf = "viga.pdf";
            String url_png = "viga.png";
            String url_jpeg = "viga_scala.jpeg";
            String url_xps = "memoria_va.xps";
            ProcessBuilder p = new ProcessBuilder();
            //ojo esto solo se está utilizando para sistema operativo windows
            p.command("cmd.exe", "/c", url_pdf);
            //p.command("cmd.exe", "/c", url_png);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(NewMDIApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_diagramaKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewMDIApplication().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenuItem contentMenuItem;
    public javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem diagrama;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem memoria;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenuItem nuevo;
    // End of variables declaration//GEN-END:variables

}
