/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acoples.visual;

import acoples.comunes.Comun;
import acoples.comunes.Estructura_Dato;
import acoples.comunes.Manipula_ficheros;
import static java.awt.Component.BOTTOM_ALIGNMENT;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Alba Proyecto
 */
public class Nombrar_pryecto extends javax.swing.JInternalFrame {

    private Manipula_ficheros mf;
    private List datos;
    public static Lista_vigas_fichero lv1;
    public static Actual act;
    private static ArrayList<String> datos1;

    /**
     * Creates new form Nombrar_pryecto
     */
    public Nombrar_pryecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre_py = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setIconifiable(true);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 1, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Defina un nombre para su proyecto:  ");
        jPanel2.add(jLabel1);

        nombre_py.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombre_pyKeyPressed(evt);
            }
        });
        jPanel2.add(nombre_py);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Accept-icon.png"))); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        aceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aceptarKeyPressed(evt);
            }
        });
        jPanel3.add(aceptar);

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Cancel-icon.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel3.add(cancelar);

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        if (nombre_py.getText().equals("") || nombre_py.getText()==null/* || nombre_py.getText().charAt(0)==' '*/) {
            JOptionPane.showMessageDialog(null, "Por favor inserte un nombre para su proyecto antes de continuar");
        } else {
            this.setVisible(false);
            dispose();
            JFileChooser jf_base = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Solo archivos con extensión .xlsx", "xlsx");
            jf_base.setFileFilter(filtro);
            int returnval = jf_base.showOpenDialog(null);
            if (returnval == JFileChooser.APPROVE_OPTION) {
                System.out.println("se tomo el archivo " + jf_base.getSelectedFile().getName());
//                System.out.println("ruta absoluta " + jf_base.getSelectedFile().getAbsolutePath());
//                System.out.println("ruta " + jf_base.getSelectedFile().getPath());
//                System.out.println("rarchivo absoluto " + jf_base.getSelectedFile().getAbsoluteFile());
//                System.out.println("existe? " + jf_base.getSelectedFile().getAbsoluteFile().exists());
                //System.out.println("secuencia  "+jf_base.getSelectedFile().getName().substring(jf_base.getSelectedFile().getName().length()-5, jf_base.getSelectedFile().getName().length()));
                mf = new Manipula_ficheros(jf_base.getSelectedFile().getAbsolutePath());
                Estructura_Dato ed = mf.lectura_fichero();
                if (jf_base.getSelectedFile().getAbsoluteFile().exists() && jf_base.getSelectedFile().getName().substring(jf_base.getSelectedFile().getName().length() - 5, jf_base.getSelectedFile().getName().length()).equals(".xlsx") && ed.getEstado() == 1) {
                    datos = ed.getLista();
//            //Comun.vs.setVisible(true);
//            //this.add(Comun.va);
//            //fileMenu.setEnabled(false);
////            Comun.py.setSecciones(datos);
////            System.out.println(Comun.py.getSecciones().size());
//            lv1=new Lista_vigas_fichero(datos);
//            
////            Comun.lv.setDatos(datos);            
////            Comun.lv.setVisible(true);
//            Comun.nm.desktopPane.add(lv1,BOTTOM_ALIGNMENT);
//            lv1.setVisible(true);
//            
//            datos1=new ArrayList<>();
//            act=new Actual(datos1);
//            Comun.nm.desktopPane.add(act,BOTTOM_ALIGNMENT);
//            act.setVisible(true);
//            
//            //vigas_acoples.setEnabled(true);
                    Ventana_calculo vc = new Ventana_calculo(datos, nombre_py.getText());
                    Comun.nm.desktopPane.add(vc, CENTER_ALIGNMENT);
                    vc.jComboBox2.requestFocus();
                    vc.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "El sistema no puede encontrar o no reconoce el archivo especificado.\nSi este fichero realmente existe, garantice que tenga la extensión y la estructura correcta.");
                }

            }
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void nombre_pyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_pyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER/* || evt.getKeyCode() == evt.VK_SPACE*/) {
            aceptar.requestFocus();
        }
    }//GEN-LAST:event_nombre_pyKeyPressed

    private void aceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aceptarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER/* || evt.getKeyCode() == evt.VK_SPACE*/) {
            if (nombre_py.getText().equals("") || nombre_py.getText()==null) {
                JOptionPane.showMessageDialog(null, "Por favor inserte un nombre para su proyecto antes de continuar");
            } else {
                this.setVisible(false);
                dispose();
                JFileChooser jf_base = new JFileChooser();
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("Solo archivos con extensión .xlsx", "xlsx");
                jf_base.setFileFilter(filtro);
                int returnval = jf_base.showOpenDialog(null);
                if (returnval == JFileChooser.APPROVE_OPTION) {
                    System.out.println("se tomo el archivo " + jf_base.getSelectedFile().getName());
//                System.out.println("ruta absoluta " + jf_base.getSelectedFile().getAbsolutePath());
//                System.out.println("ruta " + jf_base.getSelectedFile().getPath());
//                System.out.println("rarchivo absoluto " + jf_base.getSelectedFile().getAbsoluteFile());
//                System.out.println("existe? " + jf_base.getSelectedFile().getAbsoluteFile().exists());
                    //System.out.println("secuencia  "+jf_base.getSelectedFile().getName().substring(jf_base.getSelectedFile().getName().length()-5, jf_base.getSelectedFile().getName().length()));
                    mf = new Manipula_ficheros(jf_base.getSelectedFile().getAbsolutePath());
                    Estructura_Dato ed = mf.lectura_fichero();
                    if (jf_base.getSelectedFile().getAbsoluteFile().exists() && jf_base.getSelectedFile().getName().substring(jf_base.getSelectedFile().getName().length() - 5, jf_base.getSelectedFile().getName().length()).equals(".xlsx") && ed.getEstado() == 1) {
                        datos = ed.getLista();
//            //Comun.vs.setVisible(true);
//            //this.add(Comun.va);
//            //fileMenu.setEnabled(false);
////            Comun.py.setSecciones(datos);
////            System.out.println(Comun.py.getSecciones().size());
//            lv1=new Lista_vigas_fichero(datos);
//            
////            Comun.lv.setDatos(datos);            
////            Comun.lv.setVisible(true);
//            Comun.nm.desktopPane.add(lv1,BOTTOM_ALIGNMENT);
//            lv1.setVisible(true);
//            
//            datos1=new ArrayList<>();
//            act=new Actual(datos1);
//            Comun.nm.desktopPane.add(act,BOTTOM_ALIGNMENT);
//            act.setVisible(true);
//            
//            //vigas_acoples.setEnabled(true);
                        Ventana_calculo vc = new Ventana_calculo(datos, nombre_py.getText());
                        Comun.nm.desktopPane.add(vc, CENTER_ALIGNMENT);
                        vc.jComboBox2.requestFocus();
                        vc.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "El sistema no puede encontrar o no reconoce el archivo especificado.\nSi este fichero realmente existe, garantice que tenga la extensión y la estructura correcta.");
                    }

                }
            }
        }

    }//GEN-LAST:event_aceptarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nombre_py;
    // End of variables declaration//GEN-END:variables
}
